# https://hub.docker.com/_/node/
FROM node:9-alpine

RUN apk add --no-cache python \
    && python -m ensurepip \
    && rm -r /usr/lib/python*/ensurepip \
    && pip install --upgrade pip setuptools \
    && rm -r /root/.cache

RUN apk add --update make \
    && apk add g++

WORKDIR /app/

EXPOSE 8080

#CMD npm start
CMD /bin/sh -c "npm install && npm start"